version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: server
    ports:
      - "8080:8080"
  sql:
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 3+012rASIs8ionXDZgbneitqlvQ3TIBY
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: 8t1zLlN+RKZ5bFsBioJmhdA4hFvQxECO
